# Sanic + Coverage Error

In reference to https://github.com/sanic-org/sanic/issues/2345

Running `coverage run; coverage xml` against a Sanic app and tests
as shown in this example throws a bunch of warnings because the code
generated by Sanic isn't parseable.

## How to Use

* Clone this repo
* Run `./setup.sh`
* `coverage xml` will show warnings about unparseable code.

## Log

ðŸš€  ./setup.sh
created virtual environment CPython3.9.16.final.0-64 in 180ms
  creator CPython3Posix(dest=/Users/roger/code/sanic-coverage-example/venv, clear=False, no_vcs_ignore=False, global=False)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/Users/roger/Library/Application Support/virtualenv)
    added seed packages: pip==23.0.1, setuptools==67.1.0, wheel==0.38.4
  activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
[...]
Installing collected packages: sanic-routing, rfc3986, websockets, websocket-client, uvloop, ujson, tomli, sniffio, py, pluggy, packaging, multidict, iniconfig, idna, httptools, h11, coverage, certifi, attrs, aiofiles, sanic, pytest, anyio, pytest-cov, httpcore, httpx, sanic-testing
Successfully installed aiofiles-23.1.0 anyio-3.6.2 attrs-22.2.0 certifi-2022.12.7 coverage-7.2.0 h11-0.14.0 httpcore-0.16.3 httptools-0.5.0 httpx-0.23.3 idna-3.4 iniconfig-2.0.0 multidict-6.0.4 packaging-23.0 pluggy-1.0.0 py-1.11.0 pytest-7.1.2 pytest-cov-4.0.0 rfc3986-1.5.0 sanic-22.12.0 sanic-routing-22.8.0 sanic-testing-22.12.0 sniffio-1.3.0 tomli-2.0.1 ujson-5.7.0 uvloop-0.17.0 websocket-client-1.5.1 websockets-10.4
================================== test session starts ==================================
platform darwin -- Python 3.9.16, pytest-7.1.2, pluggy-1.0.0
rootdir: /Users/roger/code/sanic-coverage-example
plugins: cov-4.0.0, anyio-3.6.2
collected 1 item

tests/test_my_app.py .                                                            [100%]

=================================== 1 passed in 1.12s ===================================
/Users/roger/code/sanic-coverage-example/venv/lib/python3.9/site-packages/coverage/report.py:113: CoverageWarning: Couldn't parse '/Users/roger/code/sanic-coverage-example/_run_request_middleware': No source for code: '/Users/roger/code/sanic-coverage-example/_run_request_middleware'. (couldnt-parse)
  coverage._warn(msg, slug="couldnt-parse")
/Users/roger/code/sanic-coverage-example/venv/lib/python3.9/site-packages/coverage/report.py:113: CoverageWarning: Couldn't parse '/Users/roger/code/sanic-coverage-example/_run_response_middleware': No source for code: '/Users/roger/code/sanic-coverage-example/_run_response_middleware'. (couldnt-parse)
  coverage._warn(msg, slug="couldnt-parse")
/Users/roger/code/sanic-coverage-example/venv/lib/python3.9/site-packages/coverage/report.py:113: CoverageWarning: Couldn't parse '/Users/roger/code/sanic-coverage-example/connection_task': No source for code: '/Users/roger/code/sanic-coverage-example/connection_task'. (couldnt-parse)
  coverage._warn(msg, slug="couldnt-parse")
/Users/roger/code/sanic-coverage-example/venv/lib/python3.9/site-packages/coverage/report.py:113: CoverageWarning: Couldn't parse '/Users/roger/code/sanic-coverage-example/handle_exception': No source for code: '/Users/roger/code/sanic-coverage-example/handle_exception'. (couldnt-parse)
  coverage._warn(msg, slug="couldnt-parse")
/Users/roger/code/sanic-coverage-example/venv/lib/python3.9/site-packages/coverage/report.py:113: CoverageWarning: Couldn't parse '/Users/roger/code/sanic-coverage-example/handle_request': No source for code: '/Users/roger/code/sanic-coverage-example/handle_request'. (couldnt-parse)
  coverage._warn(msg, slug="couldnt-parse")
/Users/roger/code/sanic-coverage-example/venv/lib/python3.9/site-packages/coverage/report.py:113: CoverageWarning: Couldn't parse '/Users/roger/code/sanic-coverage-example/http1_request_header': No source for code: '/Users/roger/code/sanic-coverage-example/http1_request_header'. (couldnt-parse)
  coverage._warn(msg, slug="couldnt-parse")
/Users/roger/code/sanic-coverage-example/venv/lib/python3.9/site-packages/coverage/report.py:113: CoverageWarning: Couldn't parse '/Users/roger/code/sanic-coverage-example/http1_response_header': No source for code: '/Users/roger/code/sanic-coverage-example/http1_response_header'. (couldnt-parse)
  coverage._warn(msg, slug="couldnt-parse")
/Users/roger/code/sanic-coverage-example/venv/lib/python3.9/site-packages/coverage/report.py:113: CoverageWarning: Couldn't parse '/Users/roger/code/sanic-coverage-example/read': No source for code: '/Users/roger/code/sanic-coverage-example/read'. (couldnt-parse)
  coverage._warn(msg, slug="couldnt-parse")
/Users/roger/code/sanic-coverage-example/venv/lib/python3.9/site-packages/coverage/report.py:113: CoverageWarning: Couldn't parse '/Users/roger/code/sanic-coverage-example/send': No source for code: '/Users/roger/code/sanic-coverage-example/send'. (couldnt-parse)
  coverage._warn(msg, slug="couldnt-parse")
Wrote XML report to coverage.xml
